#!/usr/bin/env bash
set -euo pipefail

dnf install -y -q https://download.docker.com/linux/centos/7/x86_64/stable/Packages/containerd.io-1.2.6-3.3.el7.x86_64.rpm

curl -fskLS https://get.docker.com | sh
