version: "3"

services:
  api:
    image: claims_attributes_api:latest
    build: 
      context: ./src/api_service
      dockerfile: $PWD/docker/Dockerfile
    depends_on:
      - classifier
      - flashes
      - specialissues

  classifier:
    image: classifier:latest
    build: 
      context: ./src/classifier_service
      dockerfile: $PWD/docker/Dockerfile

  flashes:
    image: flashes:latest
    build: 
      context: ./src/flashes_service
      dockerfile: $PWD/docker/Dockerfile
  
  specialissues:
    image: special_issues:latest
    build: 
      context: ./src/special_issues_service
      dockerfile: $PWD/docker/Dockerfile
  
  test:
    image: caapi_test:latest
    build: 
      context: ./src/test
      dockerfile: $PWD/docker/Dockerfile
    depends_on:
      - api
      - classifier
      - flashes
      - specialissues
