# Meant to be used alongside the base `docker-compose.yml` file with a command like:
# docker-compose -f docker-compose.yml -f docker-compose..yml up -d
# See more here: https://docs.docker.com/compose/extends/#multiple-compose-files
version: "3"

services:
  api:
    image: api:${VERSION}_staging
    ports:
      - "80:8000"
    env_file:
      - src/api_service/app/docker_staging.env
    environment:
      - PORT=8000

  classifier:
    image: classifier:${VERSION}_staging
    environment:
      - PORT=8001

  flashes:
    image: flashes:${VERSION}_staging
    environment:
      - PORT=8002
   
  specialissues:
    image: specialissues:${VERSION}_staging
    environment:
      - PORT=8003

  testing:
    image: testing:${VERSION}_staging
    env_file:
      - src/api_service/tests/prod.env
    build:
      context: ./src/api_service
      dockerfile: $PWD/docker/Dockerfile
      target: test