# Meant to be used alongside the base `docker-compose.yml` file with a command like:
# docker-compose -f docker-compose.yml -f docker-compose..yml up -d
# See more here: https://docs.docker.com/compose/extends/#multiple-compose-files
version: "3"

services:
  api:
    image: 533575416491.dkr.ecr.us-gov-west-1.amazonaws.com/benefits-apis-claims-attributes:${VERSION}
    ports:
      - "80:80"
    env_file:
      - src/api_service/app/docker.env

  classifier:
    image: 533575416491.dkr.ecr.us-gov-west-1.amazonaws.com/benefits-apis-claims-attributes-classifier-service:${VERSION}

  flashes:
    image: 533575416491.dkr.ecr.us-gov-west-1.amazonaws.com/benefits-apis-claims-attributes-flashes-service:${VERSION}
   
  specialissues:
    image: 533575416491.dkr.ecr.us-gov-west-1.amazonaws.com/benefits-apis-claims-attributes-special-issues-service:${VERSION}
