# Meant to be used alongside the base `docker-compose.yml` file with a command like:
# docker-compose -f docker-compose.yml -f docker-compose.dev.yml up -d
# See more here: https://docs.docker.com/compose/extends/#multiple-compose-files
version: "3"

services:
  api:
    build: 
      target: test
    env_file:
      - src/api_service/app/docker.env
    ports:
      - "8000:8000"
    command: "regression-test"

  classifier:
    build: 
      target: test
    ports:
      - "8001:8001"
    command: "regression-test"

  flashes:
    build: 
      target: test
    ports:
      - "8002:8002"
    command: "regression-test"
  
  specialissues:
    build: 
      target: test
    ports:
      - "8003:8003"
    command: "regression-test"
