#!/usr/bin/env bash
set -euo pipefail

PEM=$1

#
# Convert the .cer to a .pem (node can't read the system .pem)
# We could just change the permissions on the system file, but
# sometimes there are checks that make sure they have not been
# tampered with, so this is safer.
#

for cert in $(find $ADDITIONAL_CA_CERTS -type f -name "*.cer")
do
  echo "Combining $cert"
  openssl x509 -inform der -in $cert >> $PEM
done
chmod 0444 $PEM
echo "Combined CA certs to $PEM"
